### ISSUE TITLE
将搜索框添加到用户列表 Add search box to user index

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#15]
![47041605506628_ pic](https://user-images.githubusercontent.com/74414333/99218213-d3a20600-2814-11eb-8a00-9e91a5e35954.jpg)

**Comment by raul-sauco** [comment]
> 我在后台检查用户列表（应该默认是内部员工的列表吧？）

否，用户列表显示所有用户。 我们需要创建用户，以便能够注册有关使用该应用程序的某人的信息并对其进行身份验证。

有不同类型的用户，例如“客户”，“用户”，“管理员”

> 我发现以客户身份建立的Lisa的信息，从小程序新建的客户信息，都会进入用户吗？

 是

> 那怎么跟原来的员工信息区分？

员工帐户的类型为“管理员”或“用户”。 客户帐户均为“客户”类型。

> 另外在用户信息中还有很多名字是字母组成的信息

这与 [#6](https://github.com/raul-sauco/minihiker-weapp/issues/6) 有关。 我们不能使用“ getUserInfo”。 我们将更新该应用程序，以要求用户更新其用户名，但在他们输入一些信息之前，我们仅使用其微信OpenID对其进行命名，这就是我们现在使用的名称。

> 不知道是怎么进入用户列表的

我不明白，您上面发送的图像是用户列表。 如果您想在“用户列表”或“用户详细信息”页面上添加/删除信息，我们可以这样做。

例如，我们可以在一个页面中统一“家庭”，“客户”和“用户”信息。

**Comment by lisaguo0** [comment]
在用户列表界面，添加一个搜索栏吧，这样方便查找，其他先不调整了

**Comment by lisaguo0** [comment]
> 在用户列表界面，添加一个搜索栏吧，这样方便查找，其他先不调整了

![屏幕快照 2020-11-24 下午12 08 10](https://user-images.githubusercontent.com/74414333/100047578-c2c54600-2e4d-11eb-98b2-087886fbd21f.png)
