### ISSUE TITLE
目前关于后台的问题，先重点修复好以下几个问题即可

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#22]
1、用户列表增加搜索框的问题
[https://github.com/raul-sauco/minihiker-webapp/issues/15#issuecomment-732038125](url)

2、又出现了客户问题无法删除的问题
![屏幕快照 2020-11-24 下午12 26 42](https://user-images.githubusercontent.com/74414333/100048733-7e877500-2e50-11eb-9651-4a4c18a07834.png)

https://backend.minihiker.com/program-group/1349/qas

3、用户付款一次，显示多次，并且显示金额为100倍的问题
[https://github.com/raul-sauco/minihiker-webapp/issues/16](url)

**Comment by raul-sauco** [comment]
让我们为每个问题使用一个线程。 我们可以使用项目委员会来组织它们。

为了引起对某个问题的关注，最好是重新发表对该问题的新评论，而不是打开重复的评论。

**Comment by lisaguo0** [comment]
> 让我们为每个问题使用一个线程。 我们可以使用项目委员会来组织它们。
> 
> 为了引起对某个问题的关注，最好是重新发表对该问题的新评论，而不是打开重复的评论。

我需要对重点问题再重新单独发起评论吗？

**Comment by raul-sauco** [comment]
> > 让我们为每个问题使用一个线程。 我们可以使用项目委员会来组织它们。
> > 为了引起对某个问题的关注，最好是重新发表对该问题的新评论，而不是打开重复的评论。
> 
> 我需要对重点问题再重新单独发起评论吗？

除非您愿意，否则无需重新发送。

我的意思是，我们不应在同一线程上遇到两个不同的问题，因为它将它们混合在一起。 不要使用发布线程来组织工作，而要使用项目板。

像这样的一个问题线程应该处理一个问题。

针对不同的问题打开不同的线程。

如果问题很紧急，请使用紧急标签，我将首先修复这些问题。

如果您有工作顺序，请使用项目板来提供项目结构。

**Comment by lisaguo0** [comment]
> > > 让我们为每个问题使用一个线程。 我们可以使用项目委员会来组织它们。
> > > 为了引起对某个问题的关注，最好是重新发表对该问题的新评论，而不是打开重复的评论。
> > 
> > 
> > 我需要对重点问题再重新单独发起评论吗？
> 
> 除非您愿意，否则无需重新发送。
> 
> 我的意思是，我们不应在同一线程上遇到两个不同的问题，因为它将它们混合在一起。 不要使用发布线程来组织工作，而要使用项目板。
> 
> 像这样的一个问题线程应该处理一个问题。
> 
> 针对不同的问题打开不同的线程。
> 
> 如果问题很紧急，请使用紧急标签，我将首先修复这些问题。
> 
> 如果您有工作顺序，请使用项目板来提供项目结构。

好的，我不太会用这个系统，我把它当成留言板来使用了
