### ISSUE TITLE
刚刚想测试合同，选择发送合同时，报错

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#26]
![WechatIMG4800](https://user-images.githubusercontent.com/74414333/100227777-9f3cf100-2f5c-11eb-88cb-968d808b2737.jpeg)

![屏幕快照 2020-11-25 下午8 25 16](https://user-images.githubusercontent.com/74414333/100227625-600ea000-2f5c-11eb-8098-01d2a07ddea4.png)

https://backend.minihiker.com/contract/send?id=19

**Comment by raul-sauco** [comment]
I broke this on fdb5120 updating the `search` method on `common\models\UserSearch` I will rename the old method to `searchYHTUser` and leave the new `search` method as the main one.
