### ISSUE TITLE
后台-合同功能，显示排序麻烦调整成按照更新时间，默认最新的排在最上面，其他的排序功能不变即可

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#27]
![屏幕快照 2020-11-26 上午11 34 31](https://user-images.githubusercontent.com/74414333/100305225-9808f800-2fdb-11eb-9f63-31bbe0fc4061.png)

**Comment by raul-sauco** [comment]
您是否可以测试并关闭它（如果需要实现的话）？ @lisaguo0

**Comment by lisaguo0** [comment]
> 您是否可以测试并关闭它（如果需要实现的话）？ @lisaguo0

刚刚进入测试了，没有问题了，已经默认最新的合同排在最上了，谢谢
