### ISSUE TITLE
后台-某个项目客户提问无法删除

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#28]
https://backend.minihiker.com/program-group/1346/qas

**Comment by raul-sauco** [comment]
您的浏览器仍在使用旧的，缓存的JavaScript和CSS。 让我们更新backservice以开始在资产上使用时间戳。 这样，浏览器将认为它们是不同的文件。

我已经发送了更新，请在有空时尝试。 该功能应正常工作。

**Comment by raul-sauco** [comment]
Closed with 90aead2
