### ISSUE TITLE
CRM无法登录

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#32]
CRM昨天开始连接不上了，很紧急，很多客户信息无法导出，麻烦帮看一下，非常感谢

<img width="903" alt="微信图片_20211229170428" src="https://user-images.githubusercontent.com/74414333/147645322-4043fbe7-4473-4900-a6af-a6524a56dc2f.png">

**Comment by raul-sauco** [comment]
The server certificate had expired, I have to find time to automate renewal, right now it is done manually and, if I forget to do so, the service goes down. Closing this as it is not related to the application and, at the moment, most of the server configuration is not under VCS.
