### ISSUE TITLE
CRM批量上传功能有问题

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-webapp#37]
Raul，你好
CRM批量上传功能有点问题，我在家里的网络可以上传，但是另外3个同事在自己家里的网络就无法批量上传表格，大家都使用chrome浏览器，请帮忙看下这个问题，应该如何解决，谢谢~

https://user-images.githubusercontent.com/74414333/171174583-b7897ec4-4b89-4899-8dd2-869ecadb998f.mp4

**Comment by raul-sauco** [comment]
The CDN that some of the assets, like Vue and xlxs.js, was using stopped working in the mainland. The functionality broke first for new users, that didn't have the old assets cached, while old users could still use it until the cached versions expired.
